// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","layout":true,"parentId":"@@/global-layout","id":"1"},"2":{"path":"/about","parentId":"@@/global-layout","id":"2"},"3":{"path":"/hud","parentId":"@@/global-layout","id":"3"},"4":{"path":"/option","parentId":"@@/global-layout","id":"4"},"5":{"path":"/*","parentId":"@@/global-layout","id":"5"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__index__index" */'@/pages/index/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__about__index" */'@/pages/about/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__hud__index" */'@/pages/hud/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__option__index" */'@/pages/option/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'F:/UGit/dota2-start/src/layouts/index.tsx')),
},
  };
}
